app_base/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('auth', views.auth, name='auth'),
    path('logout', views.user_logout, name='logout'),
]

app_editor/urls.py
from django.urls import path

from . import views


app_name = 'editor'
urlpatterns = [
    path('<int:project_id>', views.editor, name='editor'),
]

app_projects/urls.py
from django.urls import path

from . import views


app_name = 'projects'
urlpatterns = [
    path('', views.list, name='list'),
    path('create', views.create, name='create'),
    path('<int:project_id>/delete', views.delete, name='delete')
]

online_education/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_base.urls')),
    path('projects/', include('app_projects.urls')),
    path('editor/', include('app_editor.urls')),
]

projects/django_python/templates/sample_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

projects/django_python/templates/sample_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sample_app.urls'))
]

app_base/models.py
from django.db import models

# Create your models here.

app_editor/models.py
from django.db import models

# Create your models here.

app_projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from .projects import PROJECT_TYPES


PROJECT_TYPE_CHOICES = []
for types in PROJECT_TYPES.values():
    for code, name in types.items():
        PROJECT_TYPE_CHOICES.append([code, name])


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects', verbose_name=_('Пользователь'))
    name = models.CharField(max_length=128, verbose_name=_('Имя проекта'))
    description = models.TextField(blank=True, null=True, verbose_name=_('Описание проекта'))
    type = models.CharField(max_length=128, choices=PROJECT_TYPE_CHOICES, verbose_name=_('Тип проекта'))
    project_identifier = models.CharField(max_length=255, null=True, verbose_name=_('Идентификатор проекта'))
    project_folder = models.CharField(max_length=255, null=True, verbose_name=_('Расположение проекта'))


    class Meta:
        db_table = 'projects'
        verbose_name = _('проект')
        verbose_name_plural = _('проекты')

projects/django_python/templates/sample_app/models.py
from django.db import models

# Create your models here.

app_base/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, 'app_base/index.html')


def auth(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            return redirect('projects:list')
        return render(request, 'app_base/auth.html')
    else:
        return render(request, 'app_base/auth.html')


def user_logout(request):
    logout(request)
    return redirect('index')

app_editor/views.py
from django.shortcuts import render

from app_projects.models import Project
from .utils import create_project_folder, setup_project


def editor(request, project_id):
    project = Project.objects.get(id=project_id)

    if(not project.project_folder):
        create_project_folder(project)
    
    setup_project(project)

    context = {
        'project': project
    }

    return render(request, 'app_editor/editor.html', context=context)

app_projects/views.py
from django.shortcuts import render, redirect

from .models import Project
from .projects import PROJECT_TYPES, PROJECT_CATEGORIES


def list(request):
    projects = Project.objects.filter(user=request.user)

    context = {
        'projects': projects
    }

    return render(request, 'app_projects/list.html', context=context)


def create(request):
    if request.POST:
        name = request.POST['name']
        if 'description' in request.POST:
            description = request.POST['description']
        else:
            description = None
        type = request.POST['type']

        project = Project.objects.create(
            user=request.user,
            name=name,
            description=description,
            type=type
        )

        return redirect('editor:editor', project_id=project.id)
    else:
        context = {
            'project_types': PROJECT_TYPES,
            'project_categories': PROJECT_CATEGORIES,
        }
        return render(request, 'app_projects/create.html', context=context)


def delete(request, project_id):
    project = Project.objects.get(id=project_id)

    project.delete()

    return redirect('projects:list')

projects/django_python/templates/sample_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'sample_app/index.html')

app_base/templates/app_base/auth.html
{% extends 'app_base/base.html' %}

{% load i18n %}

{% block title %}{% trans 'Вход в систему' %}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center mt-5">{% trans 'Вход в систему' %}</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">{% trans 'Логин' %}</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="{% trans 'Введите ваш логин' %}">
        </div>
        <div class="form-group">
            <label for="password">{% trans 'Пароль' %}</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="{% trans 'Введите ваш пароль' %}">
        </div>
        <button type="submit" class="btn btn-primary">{% trans 'Вход' %}</button>
    </form>
</div>
{% endblock %}

app_base/templates/app_base/base.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.min.css' %}">
    {% block css %}{% endblock %}
    <title>{% block title %}Online Education{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a href="/" class="navbar-brand">Online Education</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% url 'index' as index %}
                {% if index == request.path %}
                <li class="nav-item active">
                {% else %}
                <li class="nav-item">
                {% endif %}
                    <a class="nav-link" href="/">{% trans "Главная" %}</a>
                </li>
                {% if request.user.is_authenticated %}
                    {% url 'projects:list' as projects_list %}
                    {% if projects_list in request.path %}
                <li class="nav-item active">
                    {% else %}
                <li class="nav-item">
                    {% endif %}
                    <a class="nav-link" href="{{ projects_list }}">{% trans "Мой проекты" %}</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a href="#" id="languageDropdown" class="nav-link active dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% get_available_languages as LANGUAGES %}
                        {% for code, name in LANGUAGES %}
                            {% if code == LANGUAGE_CODE %}
                            {{ name }}
                            {% endif %}
                        {% endfor %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="languageDropdown">
                        {% for code, name in LANGUAGES %}
                        <a class="dropdown-item" href="#">{{ name }}</a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
            <div>
                {% if request.user.is_authenticated %}
                <span class="ml-3 text-white font-weight-bold">{{ request.user }}</span> <a href="{% url 'logout' %}" class="text-white">({% trans "Выход" %})</a>
                {% else %}
                <a href="{% url 'auth' %}" class="btn btn-success ml-3 my-2 my-sm-0">Авторизоваться</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    {% block javascript %}{% endblock %}
</body>
</html>

app_base/templates/app_base/index.html
{% extends 'app_base/base.html' %}

{% block content %}
{% endblock %}

app_editor/templates/app_editor/editor.html
{% extends 'app_base/base.html' %}

{% load static %}
{% load i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'jstree/dist/themes/default/style.min.css' %}">
<link rel="stylesheet" href="{% static 'codemirror/lib/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'xterm/css/xterm.css' %}">
{% endblock %}

{% block title %}{% trans "Интерактивный редактор" %}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="mt-3">
        <span>{{ request.user }}/{{ project.name }}</span>
        <button id="runButton" class="btn btn-sm btn-success"><i class="fas fa-play"></i></button>
        <button id="stopButton" class="btn btn-sm btn-danger" disabled><i class="fas fa-stop"></i></button>
        <button id="restartButton" class="btn btn-sm btn-secondary" disabled><i class="fas fa-sync"></i></button>
        <span id="serverAddressLabel"></span>
    </div>
    <div class="row mt-3">
        <div class="col-2">
            <div>
                <button id="newFileButton" class="btn btn-sm btn-primary"><i class="fas fa-file"></i></button>
                <button id="newFolderButton" class="btn btn-sm btn-primary"><i class="fas fa-folder-plus"></i></button>
            </div>
            <div id="explorer"></div>
        </div>
        <div class="col-5">
            <ul id="editorTab" class="nav nav-tabs" role="tablist"></ul>
            <div id="editorPane" class="tab-content"></div>
            <div class="text-right">
                <button id="runFileButton" class="btn btn-primary"><i class="fa fa-play"></i> {% trans "Запустить файл" %}</button>
                <button id="saveFileButton" class="btn btn-primary"><i class="fa fa-save"></i> {% trans "Сохранить файл" %}</button>
            </div>
        </div>
        <div class="col-5">
            <ul id="viewTab" class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a href="#terminal" class="nav-link active" id="terminal-tab" data-toggle="tab" role="tab" aria-controls="terminal" aria-selected="true">{% trans "Терминал" %}</a>
                </li>
                <li class="nav-item">
                    <a href="#graphic" class="nav-link" id="graphic-tab" data-toggle="tab" role="tab" aria-controls="graphic" aria-selected="false">{% trans "Графика" %}</a>
                </li>
            </ul>
            <div class="tab-content" id="viewTabContent">
                <div class="tab-pane fade show active" id="terminal" role="tabpanel" aria-labelledby="terminal-tab">
                    <div id="terminalMessage"></div>
                    <div id="terminalApp"></div>
                </div>
                <div class="tab-pane fade" id="graphic" role="tabpanel" aria-labelledby="graphic-tab">ГРАФИЧЕСКИЙ ВИД</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script>
    const user = {
        id: {{ request.user.id }}
    };

    const project = {
        id: {{ project.id }},
        name: "{{ project.name }}"
    };

    const labels = {
        CREATE_FILE: "{% trans "Создать файл" %}",
        CREATE_FOLDER: "{% trans "Создать папку" %}",
    };
</script>
<script src="{% static 'xterm/lib/xterm.js' %}"></script>
<script src="{% static 'xterm-addon-attach/lib/xterm-addon-attach.js' %}"></script>
<script src="{% static 'xterm-addon-fit/lib/xterm-addon-fit.js' %}"></script>
<script src="{% static 'jstree/dist/jstree.min.js' %}"></script>
<script src="{% static 'codemirror/lib/codemirror.js' %}"></script>
<script type="module" src="{% static 'app_editor/editor.js' %}"></script>
{% endblock %}

app_projects/templates/app_projects/create.html
{% extends 'app_base/base.html' %}

{% load i18n %}

{% block title %}{% trans "Создание нового проекта" %}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center mt-5">{% trans "Создание нового проекта" %}</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">{% trans "Название проекта" %}</label>
            <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp" placeholder="{% trans 'Введите название проекта' %}">
            <small id="nameHelp" class="form-text text-muted">{% trans 'Название проекта необходимо написать на английском' %}</small>
        </div>
        <div class="form-group">
            <label for="description">{% trans "Описание проекта" %}</label>
            <textarea name="description" id="description" class="form-control" placeholder="{% trans 'Введите описание проекта' %}"></textarea>
        </div>
        <div>
            <h5>{% trans "Тип проекта" %}</h5>
            <ul class="nav nav-tabs" id="type-tabs" role="tablist">
                {% for code, name in project_categories.items %}
                <li class="nav-item">
                {% if forloop.first %}
                    <a href="#{{ code }}" id="{{ code }}-tab" class="nav-link active" data-toggle="tab" role="tab" aria-controls="{{ code }}" aria-selected="true">{{ name }}</a>
                {% else %}
                    <a href="#{{ code }}" id="{{ code }}-tab" class="nav-link" data-toggle="tab" role="tab" aria-controls="{{ code }}" aria-selected="false">{{ name }}</a>
                {% endif %}
                </li>
                {% endfor %}
            </ul>
            <div class="tab-content" id="type-content">
                {% for category, types in project_types.items %}
                {% if forloop.first %}
                <div id="{{ category }}" class="tab-pane fade show active" role="tabpanel" aria-labelledby="{{ category }}-tab">
                {% else %}
                <div id="{{ category }}" class="tab-pane fade" role="tabpanel" aria-labelledby="{{ category }}-tab">
                {% endif %}
                    {% for code, name in types.items %}
                    <input type="radio" id="{{ code }}" name="type" value="{{ code }}"> <label for="{{ code }}">{{ name }}</label><br>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="text-right">
            <a href="{% url 'projects:list' %}" class="btn btn-danger">{% trans "Отмена" %}</a>
            <button type="submit" class="btn btn-primary">{% trans "Создать проект" %}</button>
        </div>
    </form>
</div>
{% endblock %}

app_projects/templates/app_projects/list.html
{% extends 'app_base/base.html' %}

{% load i18n %}}

{% block title %}{% trans "Мои проекты" %}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center mt-5">{% trans 'Мои проекты' %}</h1>
    {% if projects %}
    <table class="table table-striped table-hover mt-3">
        <thead>
            <td>{% trans 'ID проекта' %}</td>
            <td>{% trans 'Название проекта' %}</td>
            <td>{% trans 'Описание проекта' %}</td>
            <td></td>
        </thead>
        <tbody>
            {% for project in projects %}
            <tr>
                <td>{{ project.id }}</td>
                <td><a href="{% url 'editor:editor' project.id %}">{{ project.name }}</a></td>
                <td>{{ project.description }}</td>
                <td><a href="{% url 'projects:delete' project.id %}" class="btn btn-danger">{% trans 'Удалить' %}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h4 class="text-center mt-3">{% trans 'У вас отсутствует проекты' %}</h4>
    {% endif %}
    <div class="text-center mt-3">
        <a href="{% url 'projects:create' %}" class="btn btn-primary">Создать новый проект</a>
    </div>
</div>
{% endblock %}

projects/django_python/templates/sample_app/templates/sample_app/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Мой сайт на фреймворке Django</title>
</head>
<body>
    <h1>Мой первый сайт на фреймворке Django</h1>
    <p>Теперь вы можете работать с фреймворком Django</p>
    <p>Для того чтобы получше узнать о Django, зайдите на официальный сайт</p>
</body>
</html>

projects/simple_web/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добро пожаловать</title>
</head>
<body>
    <h1>Добро пожаловать</h1>
    <p>Это ваш пример - index.html файл. Вы можете редактировать этот файл.</p>
</body>
</html>

projects/wordpress_php/templates/readme.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>WordPress &#8250; ReadMe</title>
	<link rel="stylesheet" href="wp-admin/css/install.css?ver=20100228" type="text/css" />
</head>
<body>
<h1 id="logo">
	<a href="https://wordpress.org/"><img alt="WordPress" src="wp-admin/images/wordpress-logo.png" /></a>
</h1>
<p style="text-align: center">Ваша собственная платформа для публикаций</p>

<h2>Сначала главное</h2>
<p>Добро пожаловать. WordPress для меня &#8212; очень особенный проект. Каждый разработчик и участник добавляет что-то своё, вместе мы создаём нечто прекрасное, и мне очень приятно быть частью этого. На WordPress ушли тысячи часов, и каждый день мы посвящаем его совершенствованию. Спасибо вам за то, что сделали его частью своего мира.</p>
<p style="text-align: right">&#8212; Мэтт Мулленвег</p>

<h2>Установка: Знаменитая 5-минутная установка</h2>
<ol>
	<li>Разархивируйте пакет в пустой каталог и загрузите на сервер.</li>
	<li>Откройте <span class="file"><a href="wp-admin/install.php">wp-admin/install.php</a></span> в вашем браузере. Этот скрипт поможет вам создать файл <code>wp-config.php</code> с параметрами доступа к вашей базе данных.
		<ol>
			<li>Если по какой-то причине автоматическая установка не удалась, не волнуйтесь. Она работает не на всех серверах. Откройте <code>wp-config-sample.php</code> в текстовом редакторе наподобие WordPad и заполните параметры доступа к вашей базе данных.</li>
			<li>Сохраните файл под именем <code>wp-config.php</code> и загрузите на сервер.</li>
			<li>Откройте <span class="file"><a href="wp-admin/install.php">wp-admin/install.php</a></span> в вашем браузере.</li>
		</ol>
	</li>
	<li>Как только файл конфигурации будет создан, скрипт установки создаст таблицы, необходимые для вашего сайта. Если произошла ошибка, перепроверьте ваш файл <span class="file">wp-config.php</span> и попробуйте ещё раз. Если снова не удалось, обратитесь на <a href="https://ru.wordpress.org/support/forums/">форум поддержки</a> с как можно большим количеством собранной информации.</li>
	<li><strong>Если вы не вводили пароль, запомните тот, который вам выдан.</strong> Если вы не вводили логин, им будет <code>admin</code>.</li>
	<li> Скрипт установки перенаправит вас на <a href="wp-login.php">страницу входа</a>. Войдите с логином и паролем, выбранными во время установки. Если пароль был создан автоматически, можно перейти на страницу &laquo;Профиль&raquo;, чтобы сменить его.</li>
</ol>

<h2>Обновление</h2>
<h3>Автоматическое обновление</h3>
<p>Если вы обновляетесь с версии 2.7 или выше, можно воспользоваться скриптом автоматического обновления:</p>
<ol>
	<li>Откройте <span class="file"><a href="wp-admin/update-core.php">wp-admin/update-core.php</a></span> в вашем браузере и следуйте указаниям.</li>
	<li>Вы ожидали большего? Это всё!</li>
</ol>

<h3>Обновление вручную</h3>
<ol>
	<li>Перед обновлением чего-либо убедитесь, что у вас есть резервная копия всех файлов, которые могли быть вами изменены, таких как <code>index.php</code>.</li>
	<li>Удалите ваши старые файлы WP, сохранив изменённые.</li>
	<li>Загрузите новые файлы.</li>
	<li>Откройте в браузере <span class="file"><a href="wp-admin/upgrade.php">/wp-admin/upgrade.php</a>.</span></li>
</ol>

<h2>Переход с других систем</h2>
<p>WordPress может <a href="https://codex.wordpress.org/Importing_Content">импортировать содержимое из некоторых систем</a>. Сначала нужно установить и запустить WordPress, как описано выше, затем использовать <a href="wp-admin/import.php" title="Импорт в WordPress">наши инструменты для импорта</a>.</p>

<h2>Системные требования</h2>
<ul>
	<li><a href="https://secure.php.net/">PHP</a> версии <strong>5.6.20</strong> или выше.</li>
	<li><a href="https://www.mysql.com/">MySQL</a> версии <strong>5.0</strong> или выше.</li>
</ul>

<h3>Рекомендации</h3>
<ul>
	<li><a href="https://secure.php.net/">PHP</a> версии <strong>7.3</strong> или выше.</li>
	<li><a href="https://www.mysql.com/">MySQL</a> версии <strong>5.6</strong> или выше.</li>
	<li>Модуль Apache <a href="https://httpd.apache.org/docs/2.2/mod/mod_rewrite.html">mod_rewrite</a>.</li>
	<li>Поддержка <a href="https://wordpress.org/news/2016/12/moving-toward-ssl/">HTTPS</a>.</li>
	<li>Ссылка на <a href="https://wordpress.org/">wordpress.org</a> c вашего сайта.</li>
</ul>

<h2>Сетевые ресурсы</h2>
<p>Если у вас есть любые вопросы, не касающиеся этого документа, воспользуйтесь многочисленными сетевыми ресурсами:</p>
<dl>
	<dt><a href="https://codex.wordpress.org/Заглавная_страница">Кодекс WordPress</a></dt>
		<dd>Кодекс &#8212; это энциклопедия всего, что касается WordPress. Это наиболее полный источник информации о WordPress.</dd>
	<dt><a href="https://wordpress.org/news/">Блог WordPress</a></dt>
		<dd>Здесь вы можете найти последние обновления и новости из мира WordPress. Свежие новости о WordPress по умолчанию появляются в вашей панели управления.</dd>
	<dt><a href="https://planet.wordpress.org/">Планета WordPress </a></dt>
		<dd>Планета WordPress &#8212; это новостной агрегатор, собирающий записи с блогов, посвящённых WordPress, по всему миру.</dd>
	<dt><a href="https://ru.wordpress.org/support/forums/">Форумы поддержки</a></dt>
		<dd>Если вы смотрели везде и не нашли ответа, на форумах поддержки есть большое и очень активное сообщество людей, готовых оказать помощь. Чтобы вам могли помочь, используйте информативный заголовок сообщения и сформулируйте свой вопрос максимально подробно.</dd>
	<dt><a href="https://codex.wordpress.org/IRC"><abbr title="Internet Relay Chat">IRC</abbr>-канал WordPress</a></dt>
		<dd>Существует канал онлайн-чата, который применяется для обсуждения среди людей, использующих WordPress, и иногда для поддержки. Страница по ссылке выше поможет вам попасть туда. (<a href="irc://irc.freenode.net/wordpress">irc.freenode.net #wordpress</a>)</dd>
</dl>

<h2>Последние замечания</h2>
<ul>
	<li>Если у вас есть любые предложения, идеи или комментарии, либо вы (тяжёлый вздох!) нашли ошибку, присоединяйтесь к нам на <a href="https://ru.wordpress.org/support/forums/">форуме поддержки</a>.</li>
	<li>В WordPress имеется удобный <abbr title="application programming interface">API</abbr> для плагинов, что позволяет легко расширять код. Если вас это интересует как разработчика, смотрите <a href="https://developer.wordpress.org/plugins/">справочник разработчика плагинов</a>. Файлы ядра лучше не редактировать.</li>
</ul>

<h2>Поделитесь любовью</h2>
<p>WordPress не имеет ни многомиллионной рекламной кампании, ни известных спонсоров, но у нас есть кое-что получше &#8212; вы. Если вам нравится WordPress, расскажите о нём друзьям, установите его им, поделитесь знаниями или предложите авторам статей в СМИ обратить на нас внимание.</p>

<p>WordPress &#8212; это официальное продолжение системы <a href="http://cafelog.com/">b2/caf&#233;log</a>, написанной Майклом В. Работа была продолжена <a href="https://wordpress.org/about/">разработчиками WordPress</a>. Если вы хотите поддержать WordPress &#8212; пожалуйста, рассмотрите вариант <a href="https://wordpress.org/donate/" title="Пожертвования для WordPress">пожертвования</a>.</p>

<h2>Лицензия</h2>
<p>WordPress бесплатен и опубликован под лицензией <abbr title="GNU General Public License">GPL</abbr> версии 2 или (на ваше усмотрение) более поздней. См. <a href="license.txt">license.txt</a>.</p>

</body>
</html>